name: Patch, Build with Gradle, and Push Docker Image

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-folia:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PaperMC/Folia repository
      uses: actions/checkout@v2
      with:
        repository: PaperMC/Folia

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Configure Git User Details
      run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

    - name: Gradle Apply Patches
      run: ./gradlew applyPatches

    - name: Build Reobf Paperclip
      run: ./gradlew createReobfPaperclipJar

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Folia
        path: build/libs/*folia-bundler*reobf.jar

  build-container:
    runs-on: ubuntu-latest
    needs: build-folia

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: Folia
        path: artifacts

    - name: Rename Artifact
      run: |
        file=$(find artifacts/ -type f -name 'folia-bundler-*.jar' -exec sh -c 'basename "$0" | grep -q "folia-bundler-.*-reobf.jar" && echo "$0"' {} \;)
        if [ -n "$file" ]; then
          mv "$file" /artifacts/folia.jar
          echo "File renamed to folia.jar"
        else
          echo "No file matching the pattern found"
        fi

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag v18s1:$(date +%s)
        docker tag v18s1:$(date +%s) ghcr.io/max-42/v18s1:latest
        
    - name: Push the Docker image
      run: |
        echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u max-42 --password-stdin
        docker push ghcr.io/max-42/v18s1:latest
