name: Patch and Build with Gradle

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-folia:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PaperMC/Folia repository
      uses: actions/checkout@v2
      with:
        repository: PaperMC/Folia
        #ref: ${{ github.event_name == 'pull_request' ? github.event.pull_request.head.ref : github.event.ref }}

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      run: chmod +x gradlew

    - name: Configure Git User Details
      run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

    - name: Gradle Apply Patches
      run: ./gradlew applyPatches

    #- name: Gradle Build
    #  run: ./gradlew build

    - name: Build Reobf Paperclip
      run: ./gradlew createReobfPaperclipJar

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Folia
        path: build/libs/*folia-bundler*reobf.jar

  buid-container:
    runs-on: ubuntu-latest
    needs: build-folia
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: Folia
        path: artifacts

    - name: Show files in artifacts
      run: ls -laR artifacts

    - name: Rename Artifact
      #mv artifacts/build/libs/*folia-bundler*reobf.jar artifacts/folia.jar
      run: |
        file=$(find artifacts/ -type f -name 'folia-bundler-*.jar' -exec sh -c 'basename "$0" | grep -q "folia-bundler-.*-reobf.jar" && echo "$0"' {} \;)
        if [ -n "$file" ]; then
          mv "$file" artifacts/folia.jar
          echo "File renamed to folia.jar"
        else
          echo "No file matching the pattern found"
        fi
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag v18s1:$(date +%s)


    
      
