name: Build with Gradle

on:
  push:
    branches:
      - main
      - build-folia
  pull_request:
    branches:
      - main
      - build-folia

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PaperMC/Folia repository
      uses: actions/checkout@v2
      with:
        repository: PaperMC/Folia
        #ref: ${{ github.event_name == 'pull_request' ? github.event.pull_request.head.ref : github.event.ref }}

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Gradle
      run: |
        cd Folia-Server
        chmod +x gradlew
        ./gradlew build

    - name: Upload artifact to Cache
      uses: actions/upload-artifact@v2
      with:
        name: folia-jar
        path: Folia-Server/build/libs/*.jar
